Feature/lab5
ValeryShestakovv/SwiftLabs pull request #7
Opened 2022-12-06 12:40 UTC by ValeryShestakovv

2022-12-09 06:38 UTC, andrejkrasnov requested changes

2022-12-09 06:38 UTC, andrejkrasnov commented on MarvelApp/View/DetailView/DetailViewController.swift
> +            self.imageView.image = UIImage(data: Data(referencing: viewModel.imageData))
можно вынести в метод update или setup

2022-12-09 06:38 UTC, andrejkrasnov commented on MarvelApp/View/MainView/GalleryCollectionViewCell.swift
> +    let nameLable: UILabel = {
очепятка

2022-12-09 06:38 UTC, andrejkrasnov commented on MarvelApp/View/MainView/GalleryCollectionViewCell.swift
> +            self.imageView.image = UIImage(data: Data(referencing: viewModel.imageData))
вынести в метод update

2022-12-09 06:38 UTC, andrejkrasnov commented on MarvelApp/View/MainView/GalleryCollectionViewCell.swift
> +    weak var viewModel: GalleryCellViewModal! {
forceUnwrap нельзя никогда (

2022-12-09 06:38 UTC, andrejkrasnov commented on MarvelApp/ViewController.swift
>  final class ViewController: UIViewController {
название ему бы не общее

2022-12-09 06:38 UTC, andrejkrasnov commented on MarvelApp/ViewController.swift
> +            viewModel.getListHeroes {
это бы в метод отдельный

2022-12-09 06:38 UTC, andrejkrasnov commented on MarvelApp/ViewController.swift
> +    weak var viewModel: MainViewModel! {
force unwrap

2022-12-09 06:38 UTC, andrejkrasnov commented on MarvelApp/ViewController.swift
> +        createSpinnerView()
спинер сетапиться как все остальные вьюшки это же вьюшка на этапе 
так ты кучу раз создаешь этот спинер почитай про жзненный цикл viewctonroller

2022-12-09 06:38 UTC, andrejkrasnov commented on MarvelApp/ViewController.swift
> +        if viewModel.connectedToNetwork == true {
спинер надо показывать когда запрос летит первый а не когда интернет есть

2022-12-09 06:38 UTC, andrejkrasnov commented on MarvelApp/ViewController.swift
> +        sender.endRefreshing()
заканчивать его надо когда данные прилетели а сейчас у тебя просто в момент когда пользователь дернул пулл ту рефреш сразу завершается анимашка закинь в комплишен

2022-12-09 06:38 UTC, andrejkrasnov commented on MarvelApp/ViewController.swift
> +        activityView = UIView(frame: view.bounds)
сделай верстку на autolayout

2022-12-09 06:38 UTC, andrejkrasnov commented on MarvelApp/ViewController.swift
> +            self.view.layoutIfNeeded()
тут не нужен layout if needed

2022-12-09 06:38 UTC, andrejkrasnov commented on MarvelApp/ViewController.swift
> +        self.viewModel.getAddListHeroes(indexHero: indexPath.row) {
тут логика по дерганую getAddListHerous должна быть а не в нутри viewmodel 

viewmoidel не знает как там че отрисовывается она просто страницу грузить имеет и отдает жлементы

2022-12-09 06:38 UTC, andrejkrasnov commented on MarvelApp/ViewModal/DetailView/DetailViewModal.swift
> +class DetailViewModal {
Во первых final

во вторых префикс экрана должне быть типа CharacterDetail;sViewModel

2022-12-09 06:38 UTC, andrejkrasnov commented on MarvelApp/ViewModal/DetailView/DetailViewModal.swift
> +    let id: Int
тут heromodel 

и мы обсудили что DatabaseManager должен уметь следующее

сохранять HeroModel а внутри себя создавать уже HeroModelDB и скармливать Realm и получать по id и выдавать уже сразу HeroModel

2022-12-09 06:38 UTC, andrejkrasnov commented on MarvelApp/ViewModal/DetailView/DetailViewModal.swift
> +    func downloadDetail(complition: @escaping(HeroModel) -> Void) {
должно быть не (HeroModel) -> Void)

должно быть (Result<HeroModel, Error>) -> Void)

и обработка ошибок

2022-12-14 12:56 UTC, ValeryShestakovv commented on MarvelApp/ViewController.swift
> +            self.view.layoutIfNeeded()
без него не работает анимация после прогрузки героев (collectionview после того как uiactivity исчезнет вылетает из-за границ экрана в центр)

2022-12-14 13:07 UTC, ValeryShestakovv commented on MarvelApp/ViewController.swift
> +        self.viewModel.getAddListHeroes(indexHero: indexPath.row) {
Я так понимаю что по MVVM во View не должно быть никакой логики - все во ViewModal...
+ ViewModal и не знает ничего по поводу отрисовки - в getAddListHeroes он просто скачивает героев начиная с последнего УЖЕ скаченного, формируется listHeros со старыми и подкаченными сейчас героями после чего обновляется CollectionView

2022-12-14 19:26 UTC, ValeryShestakovv commented on MarvelApp/ViewModal/DetailView/DetailViewModal.swift
> +    func downloadDetail(complition: @escaping(HeroModel) -> Void) {
Не совсем понимаю какие конкретно ошибки там следовало бы обработать(
service.getDetailsHero вернет нам result в любом случае, и в любом случае он будет нужного типа
Кажется, будто ничего непредвиденного там случиться не может...

2022-12-22 12:26 UTC, andrejkrasnov requested changes

2022-12-22 12:26 UTC, andrejkrasnov commented on MarvelApp/Model/Database/DBManager.swift
> +public class DBManager {
паблик не надо у тебя один таргет

2022-12-22 12:26 UTC, andrejkrasnov commented on MarvelApp/Model/Database/DBManager.swift
> +    }
realm будет передаваться в инициализаторе сущности

2022-12-22 12:26 UTC, andrejkrasnov commented on MarvelApp/Model/Database/DBManager.swift
> +    }
private let realm

2022-12-22 12:26 UTC, andrejkrasnov commented on MarvelApp/Model/Database/DBManager.swift
> +    static func addObjectDB<T: RealmSwiftObject>(realm: Realm?, hero: T) {
метода тогда будут не статик

2022-12-22 12:26 UTC, andrejkrasnov commented on MarvelApp/Model/Service/Service.swift
> +    func getDetailsHero(idHero: Int, completion: @escaping (HeroModel) -> Void) {
@escaping (Result<Data, Error>) -> Void

2022-12-22 12:26 UTC, andrejkrasnov commented on MarvelApp/Model/Service/Service.swift
> +                print("Error while request details hero: \(error)")
compleation Error

2023-04-08 13:50 UTC, merged